
# Name your project! Project names should contain only lowercase characters
# and underscores. A good project name should reflect your organization's
# name or the intended use of these models
name: 'analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'analytics'
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]



target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "dbt_packages"

on-run-start:
  # - '{{create_udfs()}}' # comment / uncomment this line to build UDFs called in the create_udfs macro

on-run-end:

vars:
  start_date: '1999-01-01'
  test: 'false' # to trigger runs for unit testing - override in a CLI param in testing job
  fct_order_items: 'mock_source__fct_order_items' # this is a map for unit testing
  vars:
  'dbt_date:time_zone': 'America/Los_Angeles'


flags:
  enable_iceberg_materializations: True

dbt-cloud:
  # Project details sourced from https://www.notion.so/dbtlabs/SA-Demo-Assets-fa6e16d0a9de4c07ba7511165958eea5?pvs=4#647e3924ef57460f9ab2b0eb3479c153

  # SA Demo Account (North America) - Data Analytics
  account-host: "cloud.getdbt.com"
  project-id: "206289"

  # # SA Demo Account (EMEA) - Data Analytics
  # account-host: "emea.dbt.com"
  # project-id: "921"
  # defer-env-id: "2057" # Production

  # # SA Demo Account (APAC) - Data Analytics
  # account-host: "au.dbt.com"
  # project-id: "51"

  # # SA Demo Sandbox (North America) - Data Analytics
  # account-host: "cloud.getdbt.com"
  # project-id: "291446"

  # # SA Demo Sandbox (EMEA) - Data Analytics
  # account-host: "emea.dbt.com"
  # project-id: "1429"
  # defer-env-id: "2269" # Production

  # # SA Demo Sandbox (APAC) - Data Analytics
  # account-host: "au.dbt.com"
  # project-id: "4081"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  analytics:
    staging:
      +materialized: view

    marts:
      core:
        +materialized: table
        +grants:  
          select: ['dashboard_user']
      
seeds:
  analytics:
    snowflake_contract_rates:
      +column_types:
        effective_date: DATE
        rate: NUMBER

snapshots:
  +target_schema: snapshots_dev