name: CODEOWNERS Coverage Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate-codeowners:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mszostok/codeowners-validator@v0.7.2
      with:
        github_access_token: "${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}"
        checks: "owners,duppatterns"
        experimental_checks: "notowned"
